<div class="acesseManual">
    <a target="_blank" title="Para aprender a usar o Assistente, prompts e engenharia de prompts, acesse o Manual" href="https://docs.google.com/document/d/e/2PACX-1vRsKljzHcKwRfdW7IcnFA1EHNPIInog9Mqpu58xEFzRMfZ5avrLhYbwUjPkXuTDFKFEPnev4ASJ-5Dm/pub">
        Acesse o Manual
    </a>
</div>
<div class="cards">
    <div class="botao-com-menu">
        <button type="button" class="btn btn-outline-secondary" onclick="exibirOpcoes(this)">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path fill="#35AE47" d="M0 96C0 60.7 28.7 32 64 32l132.1 0c19.1 0 37.4 7.6 50.9 21.1L289.9 96 448 96c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 480c-35.3 0-64-28.7-64-64L0 96zM64 80c-8.8 0-16 7.2-16 16l0 320c0 8.8 7.2 16 16 16l384 0c8.8 0 16-7.2 16-16l0-256c0-8.8-7.2-16-16-16l-161.4 0c-10.6 0-20.8-4.2-28.3-11.7L213.1 87c-4.5-4.5-10.6-7-17-7L64 80z" />
            </svg>
            Citar protocolo do SEI com #
        </button>
        <div class="submenu-opcoes" style="display: none;">
            <button class="submenu-item"><span class="ajude">Redigir</span> e-mail para encaminhar documento</button>
            <button class="submenu-item"><span class="ajude">Redigir</span> Ofício para dar conhecimento sobre documento</button>
            <button class="submenu-item"><span class="ajude">Redigir</span> texto jornalístico sobre decisão tomada em documento</button>
            <button class="submenu-item"><span class="ajude">Redigir</span> resumo sobre documento com lista de solicitações da requerente</button>
        </div>
    </div>

    <div class="botao-com-menu">
        <button type="button" class="btn btn-outline-secondary" onclick="exibirOpcoes(this)">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                <path fill="#EA8444" d="M64 464c-8.8 0-16-7.2-16-16L48 64c0-8.8 7.2-16 16-16l160 0 0 80c0 17.7 14.3 32 32 32l80 0 0 288c0 8.8-7.2 16-16 16L64 464zM64 0C28.7 0 0 28.7 0 64L0 448c0 35.3 28.7 64 64 64l256 0c35.3 0 64-28.7 64-64l0-293.5c0-17-6.7-33.3-18.7-45.3L274.7 18.7C262.7 6.7 246.5 0 229.5 0L64 0zm56 256c-13.3 0-24 10.7-24 24s10.7 24 24 24l144 0c13.3 0 24-10.7 24-24s-10.7-24-24-24l-144 0zm0 96c-13.3 0-24 10.7-24 24s10.7 24 24 24l144 0c13.3 0 24-10.7 24-24s-10.7-24-24-24l-144 0z" />
            </svg>
            Resumir texto
        </button>
        <div class="submenu-opcoes" style="display: none;">
            <button class="submenu-item"><span class="ajude">Resumir</span> documento destacando as solicitações</button>
            <button class="submenu-item"><span class="ajude">Resumir</span> anotações de uma reunião</button>
            <button class="submenu-item"><span class="ajude">Resumir</span> artigo de pesquisa</button>
            <button class="submenu-item"><span class="ajude">Resumir</span> relatório técnico</button>
        </div>
    </div>

    <div class="botao-com-menu">
        <button type="button" class="btn btn-outline-secondary" onclick="exibirOpcoes(this)">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                <path fill="#E2C541" d="M297.2 248.9C311.6 228.3 320 203.2 320 176c0-70.7-57.3-128-128-128S64 105.3 64 176c0 27.2 8.4 52.3 22.8 72.9c3.7 5.3 8.1 11.3 12.8 17.7c0 0 0 0 0 0c12.9 17.7 28.3 38.9 39.8 59.8c10.4 19 15.7 38.8 18.3 57.5L109 384c-2.2-12-5.9-23.7-11.8-34.5c-9.9-18-22.2-34.9-34.5-51.8c0 0 0 0 0 0s0 0 0 0c-5.2-7.1-10.4-14.2-15.4-21.4C27.6 247.9 16 213.3 16 176C16 78.8 94.8 0 192 0s176 78.8 176 176c0 37.3-11.6 71.9-31.4 100.3c-5 7.2-10.2 14.3-15.4 21.4c0 0 0 0 0 0s0 0 0 0c-12.3 16.8-24.6 33.7-34.5 51.8c-5.9 10.8-9.6 22.5-11.8 34.5l-48.6 0c2.6-18.7 7.9-38.6 18.3-57.5c11.5-20.9 26.9-42.1 39.8-59.8c0 0 0 0 0 0s0 0 0 0s0 0 0 0c4.7-6.4 9-12.4 12.7-17.7zM192 128c-26.5 0-48 21.5-48 48c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-44.2 35.8-80 80-80c8.8 0 16 7.2 16 16s-7.2 16-16 16zm0 384c-44.2 0-80-35.8-80-80l0-16 160 0 0 16c0 44.2-35.8 80-80 80z" />
            </svg>
            Sugerir
        </button>
        <div class="submenu-opcoes" style="display: none;">
            <button class="submenu-item"><span class="ajude">Sugerir</span> revisão sobre uma minuta de notícia</button>
            <button class="submenu-item"><span class="ajude">Sugerir</span> tópicos para uma apresentação</button>
            <button class="submenu-item"><span class="ajude">Sugerir</span> insights a partir de uma planilha</button>
            <button class="submenu-item"><span class="ajude">Sugerir</span> argumentos a favor de um posicionamento</button>
        </div>
        </button>

        <div class="botao-com-menu">
            <button type="button" class="btn btn-outline-secondary" onclick="exibirOpcoes(this)">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                    <path fill="#76d0eb" d="M128 0c13.3 0 24 10.7 24 24l0 40 144 0 0-40c0-13.3 10.7-24 24-24s24 10.7 24 24l0 40 40 0c35.3 0 64 28.7 64 64l0 16 0 48 0 256c0 35.3-28.7 64-64 64L64 512c-35.3 0-64-28.7-64-64L0 192l0-48 0-16C0 92.7 28.7 64 64 64l40 0 0-40c0-13.3 10.7-24 24-24zM400 192L48 192l0 256c0 8.8 7.2 16 16 16l320 0c8.8 0 16-7.2 16-16l0-256zM329 297L217 409c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47 95-95c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z" />
                </svg>
                Fazer um plano
            </button>
            <div class="submenu-opcoes" style="display: none;">
                <button class="submenu-item"><span class="ajude">Faça um plano</span> de viagem à trabalho</button>
                <button class="submenu-item"><span class="ajude">Faça um plano</span> estratégico para meu órgão</button>
                <button class="submenu-item"><span class="ajude">Faça um plano</span> tático para meu órgão</button>
                <button class="submenu-item"><span class="ajude">Faça um plano</span> de comunicação para meu órgão</button>
            </div>
            </button>

            <div class="botao-com-menu">
                <button type="button" class="btn btn-outline-secondary" onclick="exibirOpcoes(this)">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
                        <path fill="#6c71ff" d="M64 96c0-35.3 28.7-64 64-64l384 0c35.3 0 64 28.7 64 64l0 256-64 0 0-256L128 96l0 256-64 0L64 96zM0 403.2C0 392.6 8.6 384 19.2 384l601.6 0c10.6 0 19.2 8.6 19.2 19.2c0 42.4-34.4 76.8-76.8 76.8L76.8 480C34.4 480 0 445.6 0 403.2zM281 209l-31 31 31 31c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-48-48c-9.4-9.4-9.4-24.6 0-33.9l48-48c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9zM393 175l48 48c9.4 9.4 9.4 24.6 0 33.9l-48 48c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l31-31-31-31c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0z" />
                    </svg>
                    Programar
                </button>
                <div class="submenu-opcoes" style="display: none;">
                    <button class="submenu-item"><span class="ajude">Ajude</span> a depurar o meu código</button>
                    <button class="submenu-item"><span class="ajude">Ajude</span> a escrever uma função</button>
                    <button class="submenu-item"><span class="ajude">Ajude</span> a simplificar o meu código</button>
                    <button class="submenu-item"><span class="ajude">Ajude</span> a aprender Python</button>
                </div>
                </button>
            </div>