<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
        name="IaWS"
        targetNamespace="SeiIa"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
        xmlns:xmime="http://www.w3.org/2005/05/xmlmime"
        xmlns:tns="SeiIa">

    <wsdl:message name="cadastrarClassificacaoRequest">
        <wsdl:part name="IdentificacaoServico" type="xsd:string"/>
        <wsdl:part name="IdProcedimento" type="xsd:string"/>
        <wsdl:part name="Meta" type="xsd:string"/>
        <wsdl:part name="SiglaSistema" type="xsd:string"/>
    </wsdl:message>

    <wsdl:message name="cadastrarClassificacaoResponse">
        <wsdl:part name="parametros" type="tns:ArrayOfUsuarioExterno"/>
    </wsdl:message>

    <wsdl:portType name="SeiIaPortType">

        <wsdl:operation name="cadastrarClassificacao">
            <wsdl:documentation>Clasificar ODS</wsdl:documentation>
            <wsdl:input message="tns:cadastrarClassificacaoRequest"/>
            <wsdl:output message="tns:cadastrarClassificacaoResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <!-- Binding para cadastrarClassificacao usando encoded -->
    <wsdl:binding name="SeiIaBindingEncoded" type="tns:SeiIaPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="cadastrarClassificacao">
            <soap:operation soapAction="SeiIaAction"/>
            <wsdl:input>
                <soap:body namespace="SeiIa" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body namespace="SeiIa" use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="SeiIaService">
        <!-- Port para o binding SeiIaBindingEncoded -->
        <wsdl:port name="SeiIaPortServiceEncoded" binding="tns:SeiIaBindingEncoded">
            <soap:address location="[servidor]/modulos/ia/ws/IaWS.php"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
